### ISSUE TITLE
Ensure charts are stored in the correct folder

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/repo#7]
Each partner should have their own folder in the chart repository. 
Validate to ensure charts are stored appropriately on submission.

**Comment by baijum** [comment]
Part of this is handled as part of [HELM-135](https://issues.redhat.com/browse/HELM-135) where the check ensures the user is modifying only chart-related files. Intrinsically the same script also ensures the folder structure. Later there is a check to [validate user](https://github.com/openshift-helm-charts/repo/blob/ef2d3c51becc5c04d33c165746192a38344058d7/scripts/src/chartprreview/chartprreview.py#L30), that confirm the user specified in the OWNERS file is the one who makes the change.
